---
- hosts: all
  tasks:
    - name: Consulta dados
      command: sh ~/consulta_dados.sh
      register: data
    - debug: msg="{{ hostvars[inventory_hostname] }}"
    - name: Extra vars
      command: echo "{{ sispl_version }}" > test && cat test
      register: extra
    
    - name: dados
      debug: 
        var: data.stdout
    - name: extra
      debug:
        var: extra.stdout
